# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/municipality_residents', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # MunicipalityResident. As you add validations to MunicipalityResident, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      MunicipalityResident.create! valid_attributes
      get municipality_residents_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      municipality_resident = MunicipalityResident.create! valid_attributes
      get municipality_resident_url(municipality_resident)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_municipality_resident_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      municipality_resident = MunicipalityResident.create! valid_attributes
      get edit_municipality_resident_url(municipality_resident)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new MunicipalityResident' do
        expect do
          post municipality_residents_url, params: { municipality_resident: valid_attributes }
        end.to change(MunicipalityResident, :count).by(1)
      end

      it 'redirects to the created municipality_resident' do
        post municipality_residents_url, params: { municipality_resident: valid_attributes }
        expect(response).to redirect_to(municipality_resident_url(MunicipalityResident.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new MunicipalityResident' do
        expect do
          post municipality_residents_url, params: { municipality_resident: invalid_attributes }
        end.to change(MunicipalityResident, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post municipality_residents_url, params: { municipality_resident: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested municipality_resident' do
        municipality_resident = MunicipalityResident.create! valid_attributes
        patch municipality_resident_url(municipality_resident), params: { municipality_resident: new_attributes }
        municipality_resident.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the municipality_resident' do
        municipality_resident = MunicipalityResident.create! valid_attributes
        patch municipality_resident_url(municipality_resident), params: { municipality_resident: new_attributes }
        municipality_resident.reload
        expect(response).to redirect_to(municipality_resident_url(municipality_resident))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        municipality_resident = MunicipalityResident.create! valid_attributes
        patch municipality_resident_url(municipality_resident), params: { municipality_resident: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested municipality_resident' do
      municipality_resident = MunicipalityResident.create! valid_attributes
      expect do
        delete municipality_resident_url(municipality_resident)
      end.to change(MunicipalityResident, :count).by(-1)
    end

    it 'redirects to the municipality_residents list' do
      municipality_resident = MunicipalityResident.create! valid_attributes
      delete municipality_resident_url(municipality_resident)
      expect(response).to redirect_to(municipality_residents_url)
    end
  end
end
